# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20171208_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiche',
            name='quantite',
            field=models.CharField(choices=[('01', '1'), ('02', '100'), ('03', '250'), ('04', '500'), ('05', '1000'), ('06', '2000'), ('07', '3000'), ('08', '4000'), ('09', '5000'), ('10', '10000'), ('11', '50000'), ('12', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carnet',
            name='quantite',
            field=models.CharField(choices=[('01', '1'), ('02', '100'), ('03', '250'), ('04', '500'), ('05', '1000'), ('06', '2000'), ('07', '3000'), ('08', '4000'), ('09', '5000'), ('10', '10000'), ('11', '50000'), ('12', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carteservice',
            name='quantite',
            field=models.CharField(choices=[('01', '1'), ('02', '100'), ('03', '250'), ('04', '500'), ('05', '1000'), ('06', '2000'), ('07', '3000'), ('08', '4000'), ('09', '5000'), ('10', '10000'), ('11', '50000'), ('12', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cartevisite',
            name='quantite',
            field=models.CharField(choices=[('01', '1'), ('02', '100'), ('03', '250'), ('04', '500'), ('05', '1000'), ('06', '2000'), ('07', '3000'), ('08', '4000'), ('09', '5000'), ('10', '10000'), ('11', '50000'), ('12', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='casquetteblanche',
            name='quantite',
            field=models.CharField(choices=[('01', '1'), ('02', '100'), ('03', '250'), ('04', '500'), ('05', '1000'), ('06', '2000'), ('07', '3000'), ('08', '4000'), ('09', '5000'), ('10', '10000'), ('11', '50000'), ('12', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='depliant',
            name='quantite',
            field=models.CharField(choices=[('01', '1'), ('02', '100'), ('03', '250'), ('04', '500'), ('05', '1000'), ('06', '2000'), ('07', '3000'), ('08', '4000'), ('09', '5000'), ('10', '10000'), ('11', '50000'), ('12', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='farde',
            name='quantite',
            field=models.CharField(choices=[('01', '1'), ('02', '100'), ('03', '250'), ('04', '500'), ('05', '1000'), ('06', '2000'), ('07', '3000'), ('08', '4000'), ('09', '5000'), ('10', '10000'), ('11', '50000'), ('12', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='quantite',
            field=models.CharField(choices=[('01', '1'), ('02', '100'), ('03', '250'), ('04', '500'), ('05', '1000'), ('06', '2000'), ('07', '3000'), ('08', '4000'), ('09', '5000'), ('10', '10000'), ('11', '50000'), ('12', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='laniere',
            name='quantite',
            field=models.CharField(choices=[('01', '1'), ('02', '100'), ('03', '250'), ('04', '500'), ('05', '1000'), ('06', '2000'), ('07', '3000'), ('08', '4000'), ('09', '5000'), ('10', '10000'), ('11', '50000'), ('12', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pins',
            name='quantite',
            field=models.CharField(choices=[('01', '1'), ('02', '100'), ('03', '250'), ('04', '500'), ('05', '1000'), ('06', '2000'), ('07', '3000'), ('08', '4000'), ('09', '5000'), ('10', '10000'), ('11', '50000'), ('12', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='porteclef',
            name='quantite',
            field=models.CharField(choices=[('01', '1'), ('02', '100'), ('03', '250'), ('04', '500'), ('05', '1000'), ('06', '2000'), ('07', '3000'), ('08', '4000'), ('09', '5000'), ('10', '10000'), ('11', '50000'), ('12', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shoppingbag',
            name='quantite',
            field=models.CharField(choices=[('01', '1'), ('02', '100'), ('03', '250'), ('04', '500'), ('05', '1000'), ('06', '2000'), ('07', '3000'), ('08', '4000'), ('09', '5000'), ('10', '10000'), ('11', '50000'), ('12', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stylo',
            name='quantite',
            field=models.CharField(choices=[('01', '1'), ('02', '100'), ('03', '250'), ('04', '500'), ('05', '1000'), ('06', '2000'), ('07', '3000'), ('08', '4000'), ('09', '5000'), ('10', '10000'), ('11', '50000'), ('12', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='quantite',
            field=models.CharField(choices=[('01', '1'), ('02', '100'), ('03', '250'), ('04', '500'), ('05', '1000'), ('06', '2000'), ('07', '3000'), ('08', '4000'), ('09', '5000'), ('10', '10000'), ('11', '50000'), ('12', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tshirtblanc',
            name='quantite',
            field=models.CharField(choices=[('01', '1'), ('02', '100'), ('03', '250'), ('04', '500'), ('05', '1000'), ('06', '2000'), ('07', '3000'), ('08', '4000'), ('09', '5000'), ('10', '10000'), ('11', '50000'), ('12', '100000')], max_length=50),
        ),
    ]
