# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20171208_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnet',
            name='support_copie',
            field=models.CharField(choices=[('01', 'Aucun'), ('Blanc 55gr', 'Blanc 55gr'), ('Bleu 53 gr', 'Bleu 53 gr'), ('Rose 53 gr', 'Rose 53 gr'), ('Blanc 55gr avec carbone', 'Blanc 55gr avec carbone'), ('Bleu 53 gr avec carbone', 'Bleu 53 gr avec carbone'), ('Rose 53 gr avec carbone', 'Rose 53 gr avec carbone')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carnet',
            name='support_original',
            field=models.CharField(choices=[('01', 'Aucun'), ('Blanc 55gr', 'Blanc 55gr'), ('Bleu 53 gr', 'Bleu 53 gr'), ('Rose 53 gr', 'Rose 53 gr'), ('Blanc 55gr avec carbone', 'Blanc 55gr avec carbone'), ('Bleu 53 gr avec carbone', 'Bleu 53 gr avec carbone'), ('Rose 53 gr avec carbone', 'Rose 53 gr avec carbone')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carnet',
            name='support_souche',
            field=models.CharField(choices=[('01', 'Aucun'), ('Blanc 55gr', 'Blanc 55gr'), ('Bleu 53 gr', 'Bleu 53 gr'), ('Rose 53 gr', 'Rose 53 gr'), ('Blanc 55gr avec carbone', 'Blanc 55gr avec carbone'), ('Bleu 53 gr avec carbone', 'Bleu 53 gr avec carbone'), ('Rose 53 gr avec carbone', 'Rose 53 gr avec carbone')], max_length=50),
        ),
    ]
