# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20171208_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiche',
            name='quantite',
            field=models.CharField(choices=[('1', '1'), ('100', '100'), ('250', '250'), ('500', '500'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('10000', '10000'), ('50000', '50000'), ('100000', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carnet',
            name='quantite',
            field=models.CharField(choices=[('1', '1'), ('100', '100'), ('250', '250'), ('500', '500'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('10000', '10000'), ('50000', '50000'), ('100000', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carteservice',
            name='quantite',
            field=models.CharField(choices=[('1', '1'), ('100', '100'), ('250', '250'), ('500', '500'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('10000', '10000'), ('50000', '50000'), ('100000', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cartevisite',
            name='quantite',
            field=models.CharField(choices=[('1', '1'), ('100', '100'), ('250', '250'), ('500', '500'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('10000', '10000'), ('50000', '50000'), ('100000', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='casquetteblanche',
            name='quantite',
            field=models.CharField(choices=[('1', '1'), ('100', '100'), ('250', '250'), ('500', '500'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('10000', '10000'), ('50000', '50000'), ('100000', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='depliant',
            name='quantite',
            field=models.CharField(choices=[('1', '1'), ('100', '100'), ('250', '250'), ('500', '500'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('10000', '10000'), ('50000', '50000'), ('100000', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='farde',
            name='quantite',
            field=models.CharField(choices=[('1', '1'), ('100', '100'), ('250', '250'), ('500', '500'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('10000', '10000'), ('50000', '50000'), ('100000', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='quantite',
            field=models.CharField(choices=[('1', '1'), ('100', '100'), ('250', '250'), ('500', '500'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('10000', '10000'), ('50000', '50000'), ('100000', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='laniere',
            name='quantite',
            field=models.CharField(choices=[('1', '1'), ('100', '100'), ('250', '250'), ('500', '500'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('10000', '10000'), ('50000', '50000'), ('100000', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pins',
            name='quantite',
            field=models.CharField(choices=[('1', '1'), ('100', '100'), ('250', '250'), ('500', '500'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('10000', '10000'), ('50000', '50000'), ('100000', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='porteclef',
            name='quantite',
            field=models.CharField(choices=[('1', '1'), ('100', '100'), ('250', '250'), ('500', '500'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('10000', '10000'), ('50000', '50000'), ('100000', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shoppingbag',
            name='quantite',
            field=models.CharField(choices=[('1', '1'), ('100', '100'), ('250', '250'), ('500', '500'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('10000', '10000'), ('50000', '50000'), ('100000', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stylo',
            name='quantite',
            field=models.CharField(choices=[('1', '1'), ('100', '100'), ('250', '250'), ('500', '500'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('10000', '10000'), ('50000', '50000'), ('100000', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='quantite',
            field=models.CharField(choices=[('1', '1'), ('100', '100'), ('250', '250'), ('500', '500'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('10000', '10000'), ('50000', '50000'), ('100000', '100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tshirtblanc',
            name='quantite',
            field=models.CharField(choices=[('1', '1'), ('100', '100'), ('250', '250'), ('500', '500'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('10000', '10000'), ('50000', '50000'), ('100000', '100000')], max_length=50),
        ),
    ]
