# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20171208_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiche',
            name='format_papier',
            field=models.CharField(choices=[('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('1/3 A4', '1/3 A4')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carnet',
            name='format_papier',
            field=models.CharField(choices=[('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('1/3 A4', '1/3 A4')], max_length=50),
        ),
        migrations.AlterField(
            model_name='depliant',
            name='format_papier',
            field=models.CharField(choices=[('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('1/3 A4', '1/3 A4')], max_length=50),
        ),
        migrations.AlterField(
            model_name='farde',
            name='format_papier',
            field=models.CharField(choices=[('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('1/3 A4', '1/3 A4')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='format_papier',
            field=models.CharField(choices=[('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('1/3 A4', '1/3 A4')], max_length=50),
        ),
    ]
