# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20171208_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiche',
            name='face_impression',
            field=models.CharField(choices=[('Recto', 'Recto'), ('Recto/verso', 'Recto/verso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='affiche',
            name='type_papier',
            field=models.CharField(choices=[('Simple cartonné', 'Simple cartonné'), ('Papier doré', 'Papier doré'), ('Papier couché 135gr', 'Papier couché 135gr'), ('Papier couché blanc 350 gr', 'Papier couché blanc 350 gr')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carteservice',
            name='face_impression',
            field=models.CharField(choices=[('Recto', 'Recto'), ('Recto/verso', 'Recto/verso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cartevisite',
            name='face_impression',
            field=models.CharField(choices=[('Recto', 'Recto'), ('Recto/verso', 'Recto/verso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cartevisite',
            name='type_papier',
            field=models.CharField(choices=[('Simple cartonné', 'Simple cartonné'), ('Papier doré', 'Papier doré'), ('Papier couché 135gr', 'Papier couché 135gr'), ('Papier couché blanc 350 gr', 'Papier couché blanc 350 gr')], max_length=50),
        ),
        migrations.AlterField(
            model_name='depliant',
            name='face_impression',
            field=models.CharField(choices=[('Recto', 'Recto'), ('Recto/verso', 'Recto/verso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='depliant',
            name='type_papier',
            field=models.CharField(choices=[('Simple cartonné', 'Simple cartonné'), ('Papier doré', 'Papier doré'), ('Papier couché 135gr', 'Papier couché 135gr'), ('Papier couché blanc 350 gr', 'Papier couché blanc 350 gr')], max_length=50),
        ),
        migrations.AlterField(
            model_name='farde',
            name='face_impression',
            field=models.CharField(choices=[('Recto', 'Recto'), ('Recto/verso', 'Recto/verso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='farde',
            name='type_papier',
            field=models.CharField(choices=[('Simple cartonné', 'Simple cartonné'), ('Papier doré', 'Papier doré'), ('Papier couché 135gr', 'Papier couché 135gr'), ('Papier couché blanc 350 gr', 'Papier couché blanc 350 gr')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='face_impression',
            field=models.CharField(choices=[('Recto', 'Recto'), ('Recto/verso', 'Recto/verso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='type_papier',
            field=models.CharField(choices=[('Simple cartonné', 'Simple cartonné'), ('Papier doré', 'Papier doré'), ('Papier couché 135gr', 'Papier couché 135gr'), ('Papier couché blanc 350 gr', 'Papier couché blanc 350 gr')], max_length=50),
        ),
    ]
