# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20171208_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachethumide',
            name='dimension',
            field=models.CharField(choices=[('30x30mm', '30x30mm'), ('30x38mm', '30x38mm'), ('38x38mm', '38x38mm'), ('40x40mm', '40x40mm'), ('45x45mm', '45x45mm'), ('50x50mm', '50x50mm')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cachetnumerique',
            name='dimension',
            field=models.CharField(choices=[('30x30mm', '30x30mm'), ('30x38mm', '30x38mm'), ('38x38mm', '38x38mm'), ('40x40mm', '40x40mm'), ('45x45mm', '45x45mm'), ('50x50mm', '50x50mm')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cachetsec',
            name='dimension',
            field=models.CharField(choices=[('30x30mm', '30x30mm'), ('30x38mm', '30x38mm'), ('38x38mm', '38x38mm'), ('40x40mm', '40x40mm'), ('45x45mm', '45x45mm'), ('50x50mm', '50x50mm')], max_length=50),
        ),
    ]
