# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20171208_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachetimprime',
            name='type_cachet_imprime',
            field=models.CharField(choices=[('Avec manche', 'Avec manche'), ('Avec appareil Trodat', 'Avec appareil Trodat')], max_length=50),
        ),
    ]
