# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20171208_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoireshydrophore',
            name='type_accessoires_hydrophore',
            field=models.CharField(choices=[('Bougie de filtre', 'Bougie de filtre'), ('Manomètre', 'Manomètre'), ('Pressostat', 'Pressostat'), ('Pressure control', 'Pressure control'), ('Té', 'Té')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ampouleelectrique',
            name='culot',
            field=models.CharField(choices=[('E14', 'E14'), ('E27', 'E27'), ('E40', 'E40')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ampouleelectrique',
            name='forme_ampoule',
            field=models.CharField(choices=[('AR 111', 'AR 111'), ('Capsule', 'Capsule'), ('Coup de vent', 'Coup de vent'), ('Flamme', 'Flamme'), ('Goutte', 'Goutte'), ('Hélicoïdale', 'Hélicoïdale'), ('Linolite', 'Linolite'), ('Mini tube', 'Mini tube'), ('Pépite', 'Pépite'), ('Réflecteur', 'Réflecteur')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ampouleelectrique',
            name='puissance_ampoule',
            field=models.CharField(choices=[('1W', '1W'), ('3W', '3W'), ('5W', '5W'), ('6W', '6W'), ('9W', '9W'), ('10W', '10W'), ('11W', '11W'), ('12W', '12W'), ('15W', '15W'), ('18W', '18W')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ampouleelectrique',
            name='type_ampoule',
            field=models.CharField(choices=[('Economique', 'Economique'), ('Halogène', 'Halogène'), ('Incandescence', 'Incandescence'), ('Infrarouge', 'Infrarouge'), ('Led', 'Led'), ('Projecteur', 'Projecteur')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appareildemesure',
            name='tension',
            field=models.CharField(choices=[('3.6V', '3.6V'), ('10.8V', '10.8V'), ('12V', '12V'), ('24V', '24V'), ('14.4V', '14.4V'), ('18V', '18V'), ('24V', '24V'), ('24VCC', '24VCC'), ('48V', '48V'), ('240V', '240V'), ('250V', '250V')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appareildemesure',
            name='type_appareil_mesure',
            field=models.CharField(choices=[('Digital', 'Digital'), ('Mécanique', 'Mécanique'), ('Pince ampèremétrique', 'Pince ampèremétrique')], max_length=1),
        ),
        migrations.AlterField(
            model_name='balance',
            name='poids',
            field=models.CharField(choices=[('200kg', '200kg'), ('300kg', '300kg'), ('500kg', '500kg'), ('600kg', '600kg')], max_length=10),
        ),
        migrations.AlterField(
            model_name='balance',
            name='type_balance',
            field=models.CharField(choices=[('Electronique', 'Electronique'), ('Mécanique', 'Mécanique')], max_length=20),
        ),
        migrations.AlterField(
            model_name='boitecuisiniere',
            name='dimension',
            field=models.CharField(choices=[('80x80mm', '80x80mm'), ('100x100mm', '100x100mm'), ('150x150mm', '150x150mm'), ('200x150m', '200x150m')], max_length=50),
        ),
        migrations.AlterField(
            model_name='boitederivation',
            name='dimension',
            field=models.CharField(choices=[('60x60x25cm', '60x60x25cm'), ('65x65x45cm', '65x65x45cm'), ('80x80x30cm', '80x80x30cm'), ('105x105x42cm', '105x105x42cm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='boitederivation',
            name='marque',
            field=models.CharField(choices=[('ABB', 'ABB'), ('GENERAL ELECTRIC', 'GENERAL ELECTRIC'), ('SCHNEIDER', 'SCHNEIDER'), ('Suprema', 'Suprema'), ('TELEMECA', 'TELEMECA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='boitederivation',
            name='type_derivation',
            field=models.CharField(choices=[('EMBOUT', 'EMBOUT'), ('MACON', 'MACON')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chargeurbatterie',
            name='capacite_chargeur',
            field=models.CharField(choices=[('20 à 120 Ah', '20 à 120 Ah'), ('20 à 400 Ah', '20 à 400 Ah'), ('250 Ah', '250 Ah')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chargeurbatterie',
            name='marque_chargeur',
            field=models.CharField(choices=[('Einhell', 'Einhell'), ('Emergy', 'Emergy'), ('Dewalt', 'Dewalt'), ('Imo Italia', 'Imo Italia'), ('Makita', 'Makita'), ('Stihl', 'Stihl')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clefmolette',
            name='dimension_clef_molette',
            field=models.CharField(choices=[('10"', '10"'), ('12"', '12"'), ('14"', '14"'), ('36"', '36"')], max_length=50),
        ),
        migrations.AlterField(
            model_name='coffretelectrique',
            name='encastre_sailli',
            field=models.CharField(choices=[('Encastré', 'Encastré'), ('SAILLI', 'SAILLI')], max_length=20),
        ),
        migrations.AlterField(
            model_name='coffretelectrique',
            name='marque',
            field=models.CharField(choices=[('ABB', 'ABB'), ('GENERAL ELECTRIC', 'GENERAL ELECTRIC'), ('SCHNEIDER', 'SCHNEIDER'), ('Suprema', 'Suprema'), ('TELEMECA', 'TELEMECA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='compresseur',
            name='capacite_compresseur',
            field=models.CharField(choices=[('6 litres', '6 litres'), ('24 litres', '24 litres'), ('50 litres', '50 litres'), ('100 litres', '100 litres'), ('200 litres', '200 litres'), ('300 litres', '300 litres')], max_length=20),
        ),
        migrations.AlterField(
            model_name='compresseur',
            name='marque_marchine',
            field=models.CharField(choices=[('Einhell', 'Einhell'), ('Emergy', 'Emergy'), ('Dewalt', 'Dewalt'), ('Imo Italia', 'Imo Italia'), ('Makita', 'Makita'), ('Stihl', 'Stihl')], max_length=20),
        ),
        migrations.AlterField(
            model_name='compresseur',
            name='pression',
            field=models.CharField(choices=[('7 bars', '7 bars'), ('8 bars', '8 bars'), ('10 bars', '10 bars'), ('100 bars', '100 bars'), ('120 bars', '120 bars'), ('150 bars', '150 bars')], max_length=20),
        ),
        migrations.AlterField(
            model_name='compresseur',
            name='puissance_compresseur',
            field=models.CharField(choices=[('1100W', '1100W'), ('1125W', '1125W'), ('1500W', '1500W'), ('1875W', '1875W'), ('3000W', '3000W')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contacteur',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('160A', '160A'), ('200A', '200A'), ('250A', '250A'), ('400A', '400A')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contacteur',
            name='marque',
            field=models.CharField(choices=[('ABB', 'ABB'), ('GENERAL ELECTRIC', 'GENERAL ELECTRIC'), ('SCHNEIDER', 'SCHNEIDER'), ('Suprema', 'Suprema'), ('TELEMECA', 'TELEMECA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contacteur',
            name='nombre_pole',
            field=models.CharField(choices=[('2P', '2P'), ('3P', '3P'), ('4P', '4P')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contacteur',
            name='puissance',
            field=models.CharField(choices=[('4KW', '4KW'), ('5.5KW', '5.5KW'), ('7.5KW', '7.5KW'), ('11KW', '11KW'), ('55KW', '55KW')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contacteur',
            name='tension',
            field=models.CharField(choices=[('3.6V', '3.6V'), ('10.8V', '10.8V'), ('12V', '12V'), ('24V', '24V'), ('14.4V', '14.4V'), ('18V', '18V'), ('24V', '24V'), ('24VCC', '24VCC'), ('48V', '48V'), ('240V', '240V'), ('250V', '250V')], max_length=20),
        ),
        migrations.AlterField(
            model_name='controleaccesetpointage',
            name='marque_equipement',
            field=models.CharField(choices=[('ABB', 'ABB'), ('GENERAL ELECTRIC', 'GENERAL ELECTRIC'), ('SCHNEIDER', 'SCHNEIDER'), ('Suprema', 'Suprema'), ('TELEMECA', 'TELEMECA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='controleaccesetpointage',
            name='mode_fonctionnement',
            field=models.CharField(choices=[('Code', 'Code'), ('Badge', 'Badge'), ('Badge + empreinte digitale', 'Badge + empreinte digitale'), ('Empreinte digitale', 'Empreinte digitale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='controleaccesetpointage',
            name='pointage_presence',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=20),
        ),
        migrations.AlterField(
            model_name='convertisseur',
            name='Chargeur_convertisseur',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=20),
        ),
        migrations.AlterField(
            model_name='convertisseur',
            name='marque_convertisseur',
            field=models.CharField(choices=[('Victron', 'Victron'), ('Westech', 'Westech')], max_length=20),
        ),
        migrations.AlterField(
            model_name='convertisseur',
            name='puissance_convertisseur',
            field=models.CharField(choices=[('300W', '300W'), ('600W', '600W'), ('800W', '800W'), ('1000W', '1000W'), ('2000W', '2000W'), ('3000W', '3000W'), ('4000W', '4000W'), ('5000W', '5000W')], max_length=20),
        ),
        migrations.AlterField(
            model_name='convertisseur',
            name='sinus_pur',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=20),
        ),
        migrations.AlterField(
            model_name='convertisseur',
            name='tension_convertisseur',
            field=models.CharField(choices=[('12V', '12V'), ('12/24V', '12/24V'), ('24V', '24V'), ('48V', '48V')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cylindre',
            name='type_cylindre',
            field=models.CharField(choices=[('DGC', 'DGC'), ('Italy', 'Italy'), ('Renz', 'Renz'), ('Sislye', 'Sislye'), ('Vachette', 'Vachette')], max_length=50),
        ),
        migrations.AlterField(
            model_name='detecteurintrusion',
            name='mode_detection',
            field=models.CharField(choices=[('Choc', 'Choc'), ('Mouvement', 'Mouvement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='disjoncteur',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('160A', '160A'), ('200A', '200A'), ('250A', '250A'), ('400A', '400A')], max_length=50),
        ),
        migrations.AlterField(
            model_name='disjoncteur',
            name='marque',
            field=models.CharField(choices=[('ABB', 'ABB'), ('GENERAL ELECTRIC', 'GENERAL ELECTRIC'), ('SCHNEIDER', 'SCHNEIDER'), ('Suprema', 'Suprema'), ('TELEMECA', 'TELEMECA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='disjoncteur',
            name='nombre_phase',
            field=models.CharField(choices=[('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3'), ('G4', 'G4')], max_length=50),
        ),
        migrations.AlterField(
            model_name='disjoncteurmoteur',
            name='intensite',
            field=models.CharField(choices=[('6-10A', '6-10A'), ('13-17A', '13-17A'), ('17-23A', '17-23A')], max_length=50),
        ),
        migrations.AlterField(
            model_name='disjoncteurmoteur',
            name='marque',
            field=models.CharField(choices=[('ABB', 'ABB'), ('GENERAL ELECTRIC', 'GENERAL ELECTRIC'), ('SCHNEIDER', 'SCHNEIDER'), ('Suprema', 'Suprema'), ('TELEMECA', 'TELEMECA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='enregistreurcamerasurveillance',
            name='nombre_canaux',
            field=models.CharField(choices=[('16', '16')], max_length=20),
        ),
        migrations.AlterField(
            model_name='enseignelumineuse',
            name='format_enseigne',
            field=models.CharField(choices=[('Grand format', 'Grand format'), ('Petit format', 'Petit format')], max_length=20),
        ),
        migrations.AlterField(
            model_name='enseignelumineuse',
            name='longueur',
            field=models.CharField(choices=[('3m', '3m'), ('5m', '5m'), ('10', '10m'), ('1,20m', '1,20m'), ('15m', '15m'), ('20m', '20m')], max_length=20),
        ),
        migrations.AlterField(
            model_name='equerre',
            name='dimension',
            field=models.CharField(choices=[('300x400mm', '300x400mm'), ('400x600mm', '400x600mm'), ('600x800mm', '600x800mm'), ('800x100mm', '800x100mm'), ('1000x1000mm', '1000x1000mm')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flexible',
            name='utilisation',
            field=models.CharField(choices=[('Chauffe eau', 'Chauffe eau'), ('Hydrophore', 'Hydrophore'), ('Lavabo', 'Lavabo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fusible',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('160A', '160A'), ('200A', '200A'), ('250A', '250A'), ('400A', '400A')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fusible',
            name='marque',
            field=models.CharField(choices=[('ABB', 'ABB'), ('GENERAL ELECTRIC', 'GENERAL ELECTRIC'), ('SCHNEIDER', 'SCHNEIDER'), ('Suprema', 'Suprema'), ('TELEMECA', 'TELEMECA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gant',
            name='type_gant',
            field=models.CharField(choices=[('Anti chaleur', 'Anti chaleur'), ('Chantier', 'Chantier'), ('Coton', 'Coton'), ('Cuire', 'Cuire'), ('Plastique', 'Plastique')], max_length=50),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='marque_marchine',
            field=models.CharField(choices=[('Einhell', 'Einhell'), ('Emergy', 'Emergy'), ('Dewalt', 'Dewalt'), ('Imo Italia', 'Imo Italia'), ('Makita', 'Makita'), ('Stihl', 'Stihl')], max_length=20),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='moteur',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Essentiel', 'Essentiel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='puissance_groupe',
            field=models.CharField(choices=[('720W', '720W'), ('3100W', '3100W'), ('3500W', '3500W'), ('4875W', '4875W'), ('5000W', '5000W'), ('5500W', '5500W'), ('7500W', '7500W'), ('10000W', '10000W')], max_length=20),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='silencieux',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interrupteurdifferentiel',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('160A', '160A'), ('200A', '200A'), ('250A', '250A'), ('400A', '400A')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interrupteurdifferentiel',
            name='marque',
            field=models.CharField(choices=[('ABB', 'ABB'), ('GENERAL ELECTRIC', 'GENERAL ELECTRIC'), ('SCHNEIDER', 'SCHNEIDER'), ('Suprema', 'Suprema'), ('TELEMECA', 'TELEMECA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interrupteurdifferentiel',
            name='nombre_phase',
            field=models.CharField(choices=[('2P', '2P'), ('3P', '3P'), ('4P', '4P')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interrupteurdifferentiel',
            name='sensibilite',
            field=models.CharField(choices=[('30MA', '30MA'), ('300MA', '300MA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interrupteurelectrique',
            name='marque',
            field=models.CharField(choices=[('Ingelec', 'Ingelec'), ('Le grand', 'Le grand'), ('Niko', 'Niko'), ('Schneider', 'Schneider'), ('Vicko', 'Vicko')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interrupteurelectrique',
            name='schema',
            field=models.CharField(choices=[('Schéma 1', 'Schéma 1'), ('Schéma 2', 'Schéma 2'), ('Schéma 3', 'Schéma 3'), ('Schéma 4', 'Schéma 4'), ('Schéma 5', 'Schéma 5'), ('Schéma 6', 'Schéma 6'), ('Schéma 7', 'Schéma 7')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inverseur',
            name='intensite',
            field=models.CharField(choices=[('63A', '63A'), ('100A', '100A'), ('125A', '125A'), ('160A', '160A'), ('200A', '200A')], max_length=50),
        ),
        migrations.AlterField(
            model_name='machineateliernonportatif',
            name='marque_marchine',
            field=models.CharField(choices=[('Einhell', 'Einhell'), ('Emergy', 'Emergy'), ('Dewalt', 'Dewalt'), ('Imo Italia', 'Imo Italia'), ('Makita', 'Makita'), ('Stihl', 'Stihl')], max_length=20),
        ),
        migrations.AlterField(
            model_name='machineateliernonportatif',
            name='puissance_machine',
            field=models.CharField(choices=[('100W', '100W'), ('120W', '120W'), ('150W', '150W'), ('180W', '180W'), ('200W', '200W'), ('240W', '240W'), ('250W', '250W'), ('300W', '300W'), ('350W', '350W'), ('370W', '370W'), ('400W', '400W'), ('450W', '450W'), ('500W', '500W'), ('550W', '550W'), ('600W', '600W')], max_length=20),
        ),
        migrations.AlterField(
            model_name='machineateliernonportatif',
            name='type_machine_non_portatif',
            field=models.CharField(choices=[('Aspirateur', 'Aspirateur'), ('Boulonneur', 'Boulonneur'), ('Burineur', 'Burineur'), ('Coupe carrelage', 'Coupe carrelage'), ('Coupe haie', 'Coupe haie'), ('Décapeur', 'Décapeur'), ('Défonceuse', 'Défonceuse'), ('Foreuse', 'Foreuse'), ('Fraiseuse', 'Fraiseuse'), ('Marteau perforateur', 'Marteau perforateur'), ('Mélangeur', 'Mélangeur'), ('Meleuse', 'Meleuse'), ('Palan électrique', 'Palan électrique'), ('Perceuse', 'Perceuse'), ('Perforateur', 'Perforateur'), ('Pistolet à souder', 'Pistolet à souder'), ('Pompe', 'Pompe'), ('Ponceuse', 'Ponceuse'), ('Rabot', 'Rabot'), ('Raboteuse', 'Raboteuse'), ('Rainureuse', 'Rainureuse'), ('Scie', 'Scie'), ('Souffleur', 'Souffleur'), ('Tondeuse', 'Tondeuse'), ('Touret', 'Touret'), ('Tronçonneuse', 'Tronçonneuse'), ('Débroussailleuse', 'Débroussailleuse')], max_length=20),
        ),
        migrations.AlterField(
            model_name='machineatelierportatif',
            name='marque_marchine',
            field=models.CharField(choices=[('Einhell', 'Einhell'), ('Emergy', 'Emergy'), ('Dewalt', 'Dewalt'), ('Imo Italia', 'Imo Italia'), ('Makita', 'Makita'), ('Stihl', 'Stihl')], max_length=20),
        ),
        migrations.AlterField(
            model_name='machineatelierportatif',
            name='tension',
            field=models.CharField(choices=[('3.6V', '3.6V'), ('10.8V', '10.8V'), ('12V', '12V'), ('24V', '24V'), ('14.4V', '14.4V'), ('18V', '18V'), ('24V', '24V'), ('24VCC', '24VCC'), ('48V', '48V'), ('240V', '240V'), ('250V', '250V')], max_length=20),
        ),
        migrations.AlterField(
            model_name='machineatelierportatif',
            name='type_machine_portatif',
            field=models.CharField(choices=[('Visseuse', 'Visseuse')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mechebeton',
            name='diametre',
            field=models.CharField(choices=[('5mm', '5mm'), ('6mm', '6mm'), ('8mm', '8mm'), ('10mm', '10mm'), ('12mm', '12mm'), ('14mm', '14mm'), ('16mm', '16mm'), ('20mm', '20mm'), ('25mm', '25mm'), ('32mm', '32mm'), ('50mm', '50mm'), ('63mm', '63mm'), ('90mm', '90mm'), ('110mm', '110mm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='montecharge',
            name='poids',
            field=models.CharField(choices=[('1 tonne', '1 tonne'), ('2 tonnes', '2 tonnes'), ('3 tonnes', '3 tonnes'), ('4 tonnes', '4 tonnes'), ('5 tonnes', '5 tonnes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='moteurelectrique',
            name='marque_moteur',
            field=models.CharField(choices=[('Speroni', 'Speroni')], max_length=20),
        ),
        migrations.AlterField(
            model_name='moteurelectrique',
            name='nombre_pole',
            field=models.CharField(choices=[('2P', '2P'), ('3P', '3P'), ('4P', '4P')], max_length=20),
        ),
        migrations.AlterField(
            model_name='moteurelectrique',
            name='puissance_moteur',
            field=models.CharField(choices=[('180W', '180W'), ('250W', '250W'), ('370W', '370W'), ('550W', '550W'), ('750W', '750W'), ('1.1KW', '1.1KW'), ('1.5KW', '1.5KW'), ('2.2KW', '2.2KW'), ('3KW', '3KW'), ('4KW', '4KW'), ('7.5KW', '7.5KW'), ('11KW', '11KW'), ('15KW', '15KW'), ('18.5KW', '18.5KW')], max_length=20),
        ),
        migrations.AlterField(
            model_name='moteurelectrique',
            name='tension_moteur',
            field=models.CharField(choices=[('230V', '230V'), ('400V', '400V')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motopompe',
            name='moteur',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Essentiel', 'Essentiel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motopompe',
            name='puissance_moto_pompe',
            field=models.CharField(choices=[('10hp', '10hp'), ('13hp', '13hp'), ('15hp', '15hp')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motopompe',
            name='section_moto_pompe',
            field=models.CharField(choices=[('2', '2"'), ('3', '3"'), ('4', '4"')], max_length=20),
        ),
        migrations.AlterField(
            model_name='outilsjardinage',
            name='type_outils',
            field=models.CharField(choices=[('Plantoir', 'Plantoir'), ('Pinceau', 'Pinceau')], max_length=20),
        ),
        migrations.AlterField(
            model_name='palanmecanique',
            name='poids',
            field=models.CharField(choices=[('1 tonne', '1 tonne'), ('2 tonnes', '2 tonnes'), ('3 tonnes', '3 tonnes'), ('4 tonnes', '4 tonnes'), ('5 tonnes', '5 tonnes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paumelle',
            name='dimension',
            field=models.CharField(choices=[('85mm', '85mm'), ('90mm', '90mm'), ('95mm', '95mm'), ('120mm', '120mm'), ('140mm', '140mm'), ('160mm', '160mm')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pompeeau',
            name='debit_pompe',
            field=models.CharField(choices=[('300 l/h', '300 l/h'), ('600 l/h', '600 l/h'), ('1200 l/h', '1200 l/h'), ('1500 l/h', '1500 l/h'), ('1800 l/h', '1800 l/h'), ('3000 l/h', '3000 l/h'), ('3800 l/h', '3800 l/h'), ('4600 l/h', '4600 l/h'), ('6800 l/h', '6800 l/h'), ('15000 l/h', '15000 l/h'), ('15700 l/h', '15700 l/h'), ('17500 l/h', '17500 l/h'), ('18000 l/h', '18000 l/h'), ('23000 l/h', '23000 l/h')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pompeeau',
            name='hauteur_pompe',
            field=models.CharField(choices=[('5,5m', '5,5m'), ('8m', '8m'), ('9m', '9m'), ('10m', '10m'), ('11m', '11m'), ('26m', '26m'), ('36m', '36m'), ('65m', '65m'), ('90m', '90m'), ('116m', '116m')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pompeeau',
            name='marque_pompe',
            field=models.CharField(choices=[('Einhell', 'Einhell'), ('Emergy', 'Emergy'), ('Dewalt', 'Dewalt'), ('Imo Italia', 'Imo Italia'), ('Makita', 'Makita'), ('Stihl', 'Stihl')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pompeeau',
            name='puissance_pompe',
            field=models.CharField(choices=[('270W', '270W'), ('300W', '300W'), ('370W', '370W'), ('375W', '375W'), ('550W', '550W'), ('650W', '650W')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pompeforage',
            name='force_pompe',
            field=models.CharField(choices=[('900N', '900N'), ('1300N', '1300N')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pompeforage',
            name='marque_pompe',
            field=models.CharField(choices=[('Einhell', 'Einhell'), ('Emergy', 'Emergy'), ('Dewalt', 'Dewalt'), ('Imo Italia', 'Imo Italia'), ('Makita', 'Makita'), ('Stihl', 'Stihl')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pompehydrophore',
            name='capacite_pompe',
            field=models.CharField(choices=[('3000 litres', '3000 litres'), ('3800 litres', '3800 litres'), ('4100 litres', '4100 litres'), ('5500 litres', '5500 litres'), ('10500 litres', '10500 litres'), ('66000 litres', '66000 litres')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pompehydrophore',
            name='marque_pompe',
            field=models.CharField(choices=[('Einhell', 'Einhell'), ('Emergy', 'Emergy'), ('Dewalt', 'Dewalt'), ('Imo Italia', 'Imo Italia'), ('Makita', 'Makita'), ('Stihl', 'Stihl')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pompehydrophore',
            name='puissance_pompe',
            field=models.CharField(choices=[('270W', '270W'), ('300W', '300W'), ('370W', '370W'), ('375W', '375W'), ('550W', '550W'), ('650W', '650W')], max_length=20),
        ),
        migrations.AlterField(
            model_name='priseelectrique',
            name='marque',
            field=models.CharField(choices=[('Ingelec', 'Ingelec'), ('Le grand', 'Le grand'), ('Niko', 'Niko'), ('Schneider', 'Schneider'), ('Vicko', 'Vicko')], max_length=20),
        ),
        migrations.AlterField(
            model_name='priseelectrique',
            name='type_prise',
            field=models.CharField(choices=[('Antenne', 'Antenne'), ('Avec terre', 'Avec terre'), ('Cuisinière', 'Cuisinière'), ('Hermetique', 'Hermetique'), ('Murale', 'Murale'), ('Simple', 'Simple')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rallonge',
            name='longueur',
            field=models.CharField(choices=[('3m', '3m'), ('5m', '5m'), ('10', '10m'), ('1,20m', '1,20m'), ('15m', '15m'), ('20m', '20m')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reductionpvc',
            name='reduction',
            field=models.CharField(choices=[('63/50', '63/50'), ('90/63', '90/63'), ('110/90', '110/90')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sechemain',
            name='matiere',
            field=models.CharField(choices=[('Inox', 'Inox'), ('Plastique', 'Plastique')], max_length=50),
        ),
        migrations.AlterField(
            model_name='siphon',
            name='sanitaire',
            field=models.CharField(choices=[('Baignoire', 'Baignoire'), ('Evier', 'Evier'), ('Lavabo', 'Lavabo'), ('Sol', 'Sol')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tuyauterie',
            name='diametre',
            field=models.CharField(choices=[('5mm', '5mm'), ('6mm', '6mm'), ('8mm', '8mm'), ('10mm', '10mm'), ('12mm', '12mm'), ('14mm', '14mm'), ('16mm', '16mm'), ('20mm', '20mm'), ('25mm', '25mm'), ('32mm', '32mm'), ('50mm', '50mm'), ('63mm', '63mm'), ('90mm', '90mm'), ('110mm', '110mm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tuyauterie',
            name='localisation',
            field=models.CharField(choices=[('Bouchon', 'Bouchon'), ('Coude', 'Coude'), ('Manchon', 'Manchon'), ('Raccord', 'Raccord'), ('Té', 'Té'), ('Tuyau', 'Tuyau'), ('Vanne', 'Vanne')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tuyauterie',
            name='matiere_tuyauterie',
            field=models.CharField(choices=[('PPR', 'PPR'), ('PVC', 'PVC')], max_length=20),
        ),
    ]
