# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20171209_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boitederivation',
            name='dimension',
            field=models.CharField(choices=[('60x60x25mm', '60x60x25mm'), ('65x65x45mm', '65x65x45mm'), ('80x80x30mm', '80x80x30mm'), ('105x105x42mm', '105x105x42mm'), ('130x130x30mm', '130x130x30mm'), ('160x100x45mm', '160x100x45mm'), ('220x160x45mm', '220x160x45mm'), ('105x105x55mm', '105x105x55mm'), ('175x150x80mm', '175x150x80mm'), ('225x175x100mm', '225x175x100mm'), ('275x225x120mm', '275x225x120mm')], max_length=20),
        ),
    ]
