# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20171209_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacteur',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=20),
        ),
        migrations.AlterField(
            model_name='disjoncteur',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fusible',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interrupteurdifferentiel',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=50),
        ),
    ]
