# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20171209_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appareildemesure',
            name='tension',
            field=models.CharField(choices=[('3.6V', '3.6V'), ('10.8V', '10.8V'), ('12V', '12V'), ('24V', '24V'), ('14.4V', '14.4V'), ('18V', '18V'), ('24V', '24V'), ('24VCC', '24VCC'), ('48V', '48V'), ('110V', '110V'), ('220V', '220V'), ('230V', '230V'), ('240V', '240V'), ('250V', '250V'), ('380V', '380V'), ('400V', '400V')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contacteur',
            name='puissance',
            field=models.CharField(choices=[('4KW', '4KW'), ('5.5KW', '5.5KW'), ('7.5KW', '7.5KW'), ('11KW', '11KW'), ('55KW', '55KW'), ('90KW', '90KW'), ('110KW', '110KW')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contacteur',
            name='tension',
            field=models.CharField(choices=[('3.6V', '3.6V'), ('10.8V', '10.8V'), ('12V', '12V'), ('24V', '24V'), ('14.4V', '14.4V'), ('18V', '18V'), ('24V', '24V'), ('24VCC', '24VCC'), ('48V', '48V'), ('110V', '110V'), ('220V', '220V'), ('230V', '230V'), ('240V', '240V'), ('250V', '250V'), ('380V', '380V'), ('400V', '400V')], max_length=20),
        ),
        migrations.AlterField(
            model_name='machineatelierportatif',
            name='tension',
            field=models.CharField(choices=[('3.6V', '3.6V'), ('10.8V', '10.8V'), ('12V', '12V'), ('24V', '24V'), ('14.4V', '14.4V'), ('18V', '18V'), ('24V', '24V'), ('24VCC', '24VCC'), ('48V', '48V'), ('110V', '110V'), ('220V', '220V'), ('230V', '230V'), ('240V', '240V'), ('250V', '250V'), ('380V', '380V'), ('400V', '400V')], max_length=20),
        ),
    ]
