# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20171209_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motopompe',
            name='section_moto_pompe',
            field=models.CharField(choices=[('2"', '2"'), ('3"', '3"'), ('4"', '4"')], max_length=20),
        ),
    ]
