# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20171209_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampouleelectrique',
            name='puissance_ampoule',
            field=models.CharField(choices=[('1W', '1W'), ('3W', '3W'), ('5W', '5W'), ('6W', '6W'), ('9W', '9W'), ('10W', '10W'), ('11W', '11W'), ('12W', '12W'), ('15W', '15W'), ('18W', '18W'), ('32W', '32W'), ('50W', '50W'), ('60W', '60W'), ('100W', '100W'), ('200W', '200W'), ('250W', '250W'), ('400W', '400W'), ('500W', '500W'), ('1000W', '1000W')], max_length=20),
        ),
    ]
