# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20171209_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pompeeau',
            name='hauteur_pompe',
            field=models.CharField(choices=[('5,5m', '5,5m'), ('8m', '8m'), ('9m', '9m'), ('10m', '10m'), ('11m', '11m'), ('26m', '26m'), ('36m', '36m'), ('65m', '65m'), ('90m', '90m'), ('116m', '116m'), ('141m', '141m'), ('202m', '202m'), ('203m', '203m'), ('228m', '228m'), ('195m', '195m'), ('258m', '258m'), ('271m', '271m'), ('352m', '352m'), ('399m', '399m'), ('419m', '419m'), ('420m', '420m'), ('424m', '424m'), ('485m', '485m'), ('505m', '505m')], max_length=20),
        ),
    ]
