# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20171209_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pompeeau',
            name='puissance_pompe',
            field=models.CharField(choices=[('270W', '270W'), ('300W', '300W'), ('370W', '370W'), ('375W', '375W'), ('550W', '550W'), ('650W', '650W'), ('690W', '690W'), ('750W', '750W'), ('780W', '780W'), ('900W', '900W'), ('1000W', '1000W'), ('1100W', '1100W'), ('1125W', '1125W'), ('1300W', '1300W'), ('1500W', '1500W'), ('2200W', '2200W'), ('3000W', '3000W'), ('3750W', '3750W'), ('4000W', '4000W'), ('4800W', '4800W'), ('5500W', '5500W'), ('7500W', '7500W'), ('11000W', '11000W'), ('15000W', '15000W'), ('18500W', '18500W')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pompehydrophore',
            name='puissance_pompe',
            field=models.CharField(choices=[('270W', '270W'), ('300W', '300W'), ('370W', '370W'), ('375W', '375W'), ('550W', '550W'), ('650W', '650W'), ('690W', '690W'), ('750W', '750W'), ('780W', '780W'), ('900W', '900W'), ('1000W', '1000W'), ('1100W', '1100W'), ('1125W', '1125W'), ('1300W', '1300W'), ('1500W', '1500W'), ('2200W', '2200W'), ('3000W', '3000W'), ('3750W', '3750W'), ('4000W', '4000W'), ('4800W', '4800W'), ('5500W', '5500W'), ('7500W', '7500W'), ('11000W', '11000W'), ('15000W', '15000W'), ('18500W', '18500W')], max_length=20),
        ),
    ]
