# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20171209_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='moteur',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Essence', 'Essence')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motopompe',
            name='moteur',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Essence', 'Essence')], max_length=20),
        ),
    ]
