# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20171209_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampouleelectrique',
            name='forme_ampoule',
            field=models.CharField(choices=[('AR 111', 'AR 111'), ('Capsule', 'Capsule'), ('Coup de vent', 'Coup de vent'), ('Flamme', 'Flamme'), ('Goutte', 'Goutte'), ('Hélicoïdale', 'Hélicoïdale'), ('Linolite', 'Linolite'), ('Mini tube', 'Mini tube'), ('Pépite', 'Pépite'), ('Sphérique', 'Sphérique'), ('Spot', 'Spot'), ('Réflecteur', 'Réflecteur')], max_length=20),
        ),
    ]
