# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20171209_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boitecuisiniere',
            name='dimension',
            field=models.CharField(choices=[('80x80mm', '80x80mm'), ('100x100mm', '100x100mm'), ('150x150mm', '150x150mm'), ('200x150m', '200x150mm')], max_length=50),
        ),
    ]
