# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20171209_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleaccesetpointage',
            name='marque_equipement',
            field=models.CharField(choices=[('ABB', 'ABB'), ('GENERAL ELECTRIC', 'GENERAL ELECTRIC'), ('SCHNEIDER', 'SCHNEIDER'), ('Suprema', 'Suprema'), ('TELEMECA', 'TELEMECA')], max_length=50),
        ),
    ]
