# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20171209_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleaccesetpointage',
            name='mode_fonctionnement',
            field=models.CharField(choices=[('Code', 'Code'), ('Badge', 'Badge'), ('Badge + empreinte digitale', 'Badge + empreinte digitale'), ('Empreinte digitale', 'Empreinte digitale')], max_length=50),
        ),
        migrations.AlterField(
            model_name='controleaccesetpointage',
            name='pointage_presence',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=50),
        ),
    ]
