# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('presentation', models.TextField(blank=True, max_length=500, verbose_name="Présentation de l'entreprise")),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to='logos/', verbose_name='Image')),
                ('pays', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Province')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('commune', models.CharField(blank=True, max_length=100, verbose_name='Commune')),
                ('adresse', models.TextField(blank=True, max_length=500)),
                ('telephone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='E-mail')),
                ('website', models.URLField(blank=True, verbose_name='Site Web')),
                ('certifications', models.CharField(blank=True, max_length=200)),
                ('business_partners', models.CharField(blank=True, max_length=200)),
                ('business_references', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
