PIECE_RECHANGE_DIRECTION_SUSPENSION = (
		('01','Amortisseur arrière'),
		('02','Ammortisseur avant'),
		('03','Biellette stabilisatrice arrière'),
		('04','Biellette stabilisatrice avant'),
		('05','Bras de suspension inférieur'),
		('06','Bras de suspension supérieur'),
		('07','Crémaillère de direction'),
		('08','Lame maitresse'),
		('09','Pompe de direction'),
		('10','Rotule de direction exterieur'),
		('11','Rotule de direction inférieur'),
		('12','Rotule de suspension inférieur'),
		('13','Rotule de suspension supérieur'),
		('14','Silembloc bras de suspension inférieur'),
		('15','Silembloc bras de suspension supérieur'),
		('16','Silembloc stabilisatrice AV'),
		('17','Silembloc lame inférieur'),
		('18','Silembloc lame supérieur'),
		('19','Soufflet de direction'),
	)
PIECE_RECHANGE_CARROSSERIE = (
		('01','Balais essuie glace avant'),
		('02','Feu arrière gauche'),
		('03','Feu arrière droite'),
		('04','Phare avant gauche'),
		('05','Phare avant droite'),
		('06','Retroviseur gauche'),
		('07','Retroviseur droite'),
	)
PIECE_RECHANGE_ELECTRIQUE = (
		('01','Alternateur'),
		('02','Contacteur de pression d\'huile'),
		('03','Demarreur'),
		('04','Intercepteur de température'),
		('05','Pompe à vide alternateur'),
		('06','Relais de démarrage'),
	)
PIECE_RECHANGE_EMBRAYAGE = (
		('01','Butée embrayage'),
		('02','Cylindre émetteur'),
		('03','Cylindre récepteur'),
		('04','Disque embrayage'),
		('05','Kit de réparation cylindre récepteur'),
		('06','Kit de réparation cylindre emetteur'),
		('07','Plateau embrayage'),
	)
PIECE_RECHANGE_FREINAGE = (
		('01','Cylindre de roue arrière gauche'),
		('02','Cylindre de roue arrière droite'),
		('03','Disque de frein avant'),
		('04','Disque/tambour de frein arrière'),
		('05','Maitre cylindre'),
		('06','Plaquette de frein avant'),
		('07','Plaquette / machoir de frein arrière'),
	)
PIECE_RECHANGE_REFROIDISSEMENT = (
		('1','Accouplement hydraulique'),
		('2','Bouchon radiateur'),
		('3','Courroie alternateur'),
		('4','Pompe à eau'),
		('5','Radiateur'),
		('6','Thermostat'),
		('7','Ventilateur'),
	)
PIECE_RECHANGE_MOTEUR = (
		('01','Bougie'),
		('02','Courroie alternateur'),
		('03','Courroie compresseur'),
		('04','Courroie de distribution'),
		('05','Courroie de direction'),
		('06','Courroie pompe allerte'),
		('07','Filtre à air'),
		('08','Filtre à carburant'),
		('09','Filtre à huile'),
		('10','Filtre habitacle'),
		('11','Injecteur complet'),
		('12','Nez injecteur'),
		('13','Pompe à carburant'),
		('14','Pompe à huile'),
		('15','Support moteur'),
		('16','Tendeur alternateur'),
		('17','Tendeur de distribution'),
		('18','Tendeur distributeur'),
		('19','Turbo compresseur'),
	)
PIECE_RECHANGE_TRANSMISSION = (
		('01','Ecrou de roue arrière'),
		('02','Ecrou de roue avant'),
		('03','Goujon de roue arrière'),
		('04','Goujon de roue avant'),
		('05','Croisillon 1'),
		('06','Croisillon 2'),
		('07','Kit de roulement de roue arrière'),
		('08','Kit de roulement de roue avant'),
		('09','Kit roulement de roue avant droite'),
		('10','Moyeu avant gauche'),
		('11','Palier de transmission'),
		('12','Roulement Moyeu arrière'),
		('13','Soufflet de transmission'),
	)
PIECE_REVISION_MOTEUR = (
		('01','Bielle moteur'),
		('02','Chemise (jeux de 4 pcs)'),
		('03','Coussinet bielle'),
		('04','Coussinet latéral'),
		('05','Coussinet palier'),
		('06','Joint de culasse'),
		('07','Piston (sans segment)'),
		('08','Pochette de joint'),
		('09','Retient huile'),
		('10','Segments'),
	)

ANNEE_DEBUT_FABRICATION_VEHICULE = (
		('01','2002'),
		('02','2003'),
		('03','2004'),
		('04','2005'),
		('05','2006'),
		('06','2007'),
		('07','2008'),
		('08','2009'),
		('09','2010'),
		('10','2011'),
		('11','2012'),
		('12','2013'),
		('13','2014'),
		('14','2015'),
		('15','2016'),
		('16','2017'),
	)

ANNEE_FIN_FABRICATION_VEHICULE = (
		('01','2002'),
		('02','2003'),
		('03','2004'),
		('04','2005'),
		('05','2006'),
		('06','2007'),
		('07','2008'),
		('08','2009'),
		('09','2010'),
		('10','2011'),
		('11','2012'),
		('12','2013'),
		('13','2014'),
		('14','2015'),
		('15','2016'),
		('16','2017'),
	)